export const icons = [
    { name: 'sushi', emojiCode: 0x1F363 },
    { name: 'gelato', emojiCode: 0x1F366 },
    { name: 'biscotti', emojiCode: 0x1F36A },
    { name: 'torta', emojiCode: 0x1F382 },
    { name: 'cioccolata', emojiCode: 0x1F36B },
    { name: 'cocktail', emojiCode: 0x1F379 },
    { name: 'pasta', emojiCode: 0x1F35D },
    { name: 'insalata', emojiCode: 0x1F957 },
    { name: 'frittata', emojiCode: 0x1F958 },
    { name: 'uovo', emojiCode: 0x1F373 },
    { name: 'toast', emojiCode: 0x1F96A },
    { name: 'panino', emojiCode: 0x1F354 },
    { name: 'pizza', emojiCode: 0x1F355 },
    { name: 'carne', emojiCode: 0x1F969 },
    { name: 'pollo', emojiCode: 0x1F357 },
    { name: 'formaggio', emojiCode: 0x1F9C0 },
    { name: 'vegetali', emojiCode: 0x1F96C },
    { name: 'pesce', emojiCode: 0x1F41F },
    { name: 'crostacei', emojiCode: 0x1F99E },
    { name: 'molluschi', emojiCode: 0x1F419 },
    { name: 'default', emojiCode: 0x1f37d },
];